#!/usr/bin/env bash

# Create PID file
echo $$ > /tmp/myscript.pid

# SIGTERM handler
handle_sigterm() {
    echo "I hate the kill command"
    rm -f /tmp/myscript.pid
    exit 0
}

# SIGINT handler
handle_sigint() {
    echo "Y U no love me?!"
}

# SIGQUIT handler
handle_sigquit() {
    rm -f /tmp/myscript.pid
    exit 0
}

# traps
trap handle_sigterm SIGTERM
trap handle_sigint SIGINT
trap handle_sigquit SIGQUIT

# infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
~                                                             
